name: Node-Bun Parity Tests

on:
  workflow_dispatch:

jobs:
  format:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Install Dependencies
        run: bun install

      - name: Test `bun install` for target repos
        run: bun test-install